### ISSUE TITLE
Less strict node version check

### ISSUE THREAD

**Issue by ambroseus** [mykolaharmash/git-jump#2]
Guess current supported node version `"node": ">=12.18.2"` is too strict
For ex. I can't use `git-jump` while my node version is 12.18.1
![Selection_022](https://user-images.githubusercontent.com/380645/93447088-b0251280-f8da-11ea-9259-e2bfc1f98e81.png)

**Comment by ambroseus** [comment]
Have proposition to allow any version >=12.*

**Comment by mykolaharmash** [comment]
Totally agree. Please update to `v0.1.14`, now it requires node `>=12.12.0`. 

12.12.0 it's the version where `fs.opendirSync()` API was introduced, and I use it in git-jump, so it's the lowest it can go without some major changes.

**Comment by ambroseus** [comment]
awesome! :smile:  thanks for the quick resolution!

**Comment by ambroseus** [comment]
now I have new alias)
![Selection_024](https://user-images.githubusercontent.com/380645/93465038-df477e00-f8f2-11ea-8ff2-dc2eac8a5df4.png)

**Comment by mykolaharmash** [comment]
Awesome😀 thank you again for taking time to report the issue!
