### ISSUE TITLE
Is it possible to install git-jump on windows ?

### ISSUE THREAD

**Issue by yhelioui** [mykolaharmash/git-jump#5]
Hello there,

Sorry for creating an issue for such question but I am wondering if we can use git-jump on windows via Cmder ?

Thanks,
Youssef

**Comment by mykolaharmash** [comment]
Hey! No worries. Yes, sure, you can use git-jump on Windows. I don't use it on Windows regularly but tested all major features there and it works without problems as far as I can tell. 

I'll leave this issue open for a couple of days, would be great if you could try it out and confirm that all good on your side. If you find any issues, please let me know, will try to fix them asap.

**Comment by yhelioui** [comment]
Thanks a lot for your quick feedback ! :)
Should I use any package manager or can install it manually ?

To be frank I could not find an easy way to install homebrew or npm on Windows :(

**Comment by mykolaharmash** [comment]
Ah, I see. You need to install Node.js, NPM comes with it by default, just grab [the Node.js installer for Windows](https://nodejs.org/en/download/) from the official site.

**Comment by mykolaharmash** [comment]
Hope everything worked out eventually. In case you have any problems feel free to open a new issue, I'll close this one.
